### PR TITLE
Integrate new plug.Helpers commands (Register and Execute command)

### PR DESCRIPTION
**Pull request by ethervoid**
Related to https://github.com/mattermost/mattermost-server/pull/11890

This is an example where I want to show how the new Plugin helper methods are integrated into a working plugin.

We've changed all the `command.RegisterCommand` and `command.ExecuteComand` by `plugin.RegisterCommand` and `plugin.ExecuteCommand`

**There is one thing left to change and is the version of mattermost-server in the go.mod file**

### CODE REVIEW

**Comment by ethervoid** [comment]
Since this changes are taking by another person I'd close this PR

**Comment by jasonblais** [comment]
@ethervoid Sure thing. Before closing would there be a link to a ticket or discussion that includes the next steps (such as someone else taking over the changes)?

**Comment by ethervoid** [comment]
@jasonblais Yes, [here](https://github.com/mattermost/mattermost-server/issues/11843#issuecomment-559552692) is where the assign changed

**Comment by jasonblais** [comment]
Thanks! Looks like I can't close the issue so @ethervoid you can go ahead :)

**Pull request closed without merging**
