### PR TITLE
MM-24503 Adding custom route example.

### PR DESCRIPTION
**Pull request by crspeller**
#### Summary
Adding example of route registration added in: https://github.com/mattermost/mattermost-webapp/pull/5367

Routes can be found at:
- `/plug/com.mattermost.demo-plugin/roottest`
- `/<teamname>/com.mattermost.demo-plugin/teamtest`

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24503

### CODE REVIEW

**Comment by crspeller** [comment]
@hanzei Thanks! I had no idea that file existed.

**Comment by marianunez** [comment]
Could we add a link to the new routes? In the root modal or the RHS possibly so that they are easily accesible within the plugin UI?

**Comment by lieut-data** [comment]
Agree with @marianunez -- I think it's important that the links are in the main webapp, so we can also verify that navigation occurs without refreshing the page.

**Comment by crspeller** [comment]
@marianunez @lieut-data Ya that makes a lot of sense. An example of how to make it not refresh is a good idea. 

Added some links to the RHS.

**Comment by prapti** [comment]
@crspeller While I'm going to review this PR (and the associated web PR) after @cpoile's review is completed, I was wondering that to test that there was no page refresh, verifying that no HTTP requests was sent when clicking that link on the demo-RHS or following that link from the address bar would be a way to test it.

**Comment by crspeller** [comment]
@prapti Yes that sounds reasonable.

**Pull request merged**
