### PR TITLE
Add nightly builds

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Build the plugin every day to spot broken builds earlier. I'm 0/5 on weekly/daily. Thoughts?

#### Ticket Link
https://community.mattermost.com/core/pl/pxb4cdusbtytxdgyd3zde5fd9a

### CODE REVIEW

**Comment by hanzei** [comment]
@mattermost/integrations Let me know if you have any feedback

**Comment by hanzei** [comment]
Let's wait a few day for feedback from @mattermost/integrations

**Comment by mickmister** [comment]
@hanzei Can a failed build be reported to a channel for us to see?

**Comment by hanzei** [comment]
@mickmister Awesome idea :+1: Unfortunately, sending notifications is tricky given the way the circleci is configured. I added the idea to https://mattermost.atlassian.net/wiki/spaces/INT/pages/570818730/Plugin+CI+overhaul

**Pull request merged**
