### PR TITLE
Release v0.1

### PR DESCRIPTION
**Pull request by hanzei**
Follow up from https://github.com/mattermost/mattermost-plugin-demo/pull/26#issuecomment-482157294

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann let me know if you have any questions about the expected behaviour of the plugin

**Comment by DHaussermann** [comment]
@hanzei  I have pulled this repo and when I use `make` to build the demo plugin I'm still seeing the version as `0.06` and not `0.1.0` 
Is it possible it's still building with the old version number?

**Comment by jasonblais** [comment]
Is there a way to test this @hanzei?

**Comment by hanzei** [comment]
In my mind https://github.com/mattermost/mattermost-plugin-demo/blob/master/server/README.md and https://github.com/mattermost/mattermost-plugin-demo/blob/master/webapp/README.md define the expected behaviour. This should be tested.

**Comment by jasonblais** [comment]
@hanzei Can you help provide Dylan a binary that he can use to test?

**Comment by hanzei** [comment]
I build a bundle and posted it on community. See https://community.mattermost.com/core/pl/twkiu4jc1frh587yfc9gfn98dy

**Comment by hanzei** [comment]
@DHaussermann @jasonblais I would like to move forward with this. I could test the plugin myself, if this helps.

**Comment by jasonblais** [comment]
@DHaussermann Do we use the Demo Plugin for release testing? If so, maybe we can use Hanzei's version for testing we'll do in the coming days.

**Comment by hanzei** [comment]
@DHaussermann Gentle reminder about this.

**Comment by DHaussermann** [comment]
My sincere apologies @hanzei I will try to get this done tomorrow.

**Comment by hanzei** [comment]
@DHaussermann let me know, if you need a new bundle

**Comment by DHaussermann** [comment]
Hi @hanzei,

I have looked over the documentation you linked and tested the plugin. There are a couple things I noticed here. 

1. When I upgrade from 0.0.6 to the 1.0.0 bundle you provided some time ago I notice that `/crash` and `/ephemeral` do not exist. Unless I'm misunderstanding, your code change is to updates the version number. Maybe these  2 commands were put in after you build the bundle from `release_0.1`? Should I try to rebuild the bundle form your branch to see if these changes are present or is it fine to test once in master? 

2. For `This demo implementation logs a message to demo channel whenever a new user is created.` I'm not seeing this work. I create users using the regular account creation flow and do not see it logged to the channel as expected.  Any thoughts on this?

**Comment by hanzei** [comment]
Hi @DHaussermann,

1. > your code change is to updates the version number. Maybe these 2 commands were put in after you build the bundle from `release_0.1`
Yes

**Comment by DHaussermann** [comment]
To clarify point 2. above regarding the user creation message, this was not specific to the 1.0.0 bundle and this code change. I will investigate this further and create a separate issue if needed.

**Comment by hanzei** [comment]
Hi @DHaussermann,

#### 1
> your code change is to updates the version number. Maybe these 2 commands were put in after you build the bundle from `release_0.1`

Yes, that is correct. Sorry for the confusion. I send you a new bundle via DM.

#### 2
Good catch. I found the cause of this issue and submitted a PR to fix it.

**Pull request merged**
