### PR TITLE
Add example usage of number type

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
I tried to come up with a creative example usage but ended up just copying the code from `RandomSecret`. I'm open for ideas.

Screenshot from 2020-02-03 10-21-06
Screenshot from 2020-02-03 10-21-14
Screenshot from 2020-02-03 10-21-45

#### Ticket Link
Follow up on https://github.com/mattermost/mattermost-server/pull/13800

### CODE REVIEW

**Comment by prapti** [comment]
@hanzei I am not seeing the described behavior - the secret number is not getting published by the demo plugin bot; but before we even get there, I'm getting the following error on the first installation of the demo plugin:
```
DEBU[2020-02-04T14:59:44.381527-08:00] using plugin                                  caller="plugin/hclog_adapter.go:51" plugin_id=com.mattermost.demo-plugin wrapped_extras=version1
ERRO[2020-02-04T14:59:44.485443-08:00] SqlUserStore.Get: We encountered an error finding the account, SqlUserStore.Get: Unable to find the user., user_id=com.mattermost.demo-plugin  caller="app/bot.go:35"
ERRO[2020-02-04T14:59:45.876241-08:00]  call to OnConfigurationChange failed, error: failed to ensure demo bot.: failed to create bot: SqlUserStore.Get: We encountered an error finding the account, SqlUserStore.Get: Unable to find the user., user_id=com.mattermost.demo-plugin  caller="go-plugin/stream.go:15" plugin_id=com.mattermost.demo-plugin source=plugin_stderr
WARN[2020-02-04T14:59:45.88013-08:00] No demo channel id for team                   caller="mlog/sugar.go:27" plugin_id=com.mattermost.demo-plugin team=ig4wsojattnsxq4yksmqybpd6r
WARN[2020-02-04T14:59:45.880445-08:00] No demo channel id for team                   caller="mlog/sugar.go:27" plugin_id=com.mattermost.demo-plugin team=tgrmkn5skfrg3fwb7kbefsbs6r
ERRO[2020-02-04T14:59:45.945251-08:00] failed to post ChannelHasBeenCreated message  caller="mlog/sugar.go:23" channel_id=g46ptoo8efdh3yzw7cjgxwfb7y error="SqlChannelStore.Get: Unable to find the existing channel, id=" plugin_id=com.mattermost.demo-plugin
ERRO[2020-02-04T14:59:45.9608068-08:00] failed to post ChannelHasBeenCreated message  caller="mlog/sugar.go:23" channel_id=rdafxeqnq78tdxoqc4btmogzdh error="SqlChannelStore.Get: Unable to find the existing channel, id=" plugin_id=com.mattermost.demo-plugin
```

**Comment by hanzei** [comment]
@prapti This is yet another instance of https://mattermost.atlassian.net/browse/MM-22106. The first time the demo plugin starts it's expected to error.

Would you please disable and enable the plugin and try again?

**Comment by prapti** [comment]
Thanks @hanzei!
I'm not getting a bot message about my secret number though. Do I need to do anything for this?

**Comment by hanzei** [comment]
@prapti Just to double check: The message is expected to be shown in the demo plugin channel. Can you confirm that you don't see it there?

**Comment by prapti** [comment]
> @prapti Just to double check: The message is expected to be shown in the demo plugin channel. Can you confirm that you don't see it there?

@hanzei Yeah, the demo plugin bot is not sending any message about the secret number. The bot DM is empty.

**Comment by hanzei** [comment]
It should not show up in the bot DM, but in a channel which you configure via `Channel Name` in the plugin settings.

**Pull request merged**
