### PR TITLE
Fix invalid parameter for openInteractiveDialog

### PR DESCRIPTION
**Pull request by kaakaa**
#### Summary
This PR fix the issue that interactive dialog opened from main menu doesn't work fine.

[screen.webm](https://github.com/mattermost/mattermost-plugin-demo/assets/1453749/9639bc2c-6e68-4958-95fa-7a476cfdeb2b)

#### Ticket Link
N/A

### CODE REVIEW

**Review by hanzei — APPROVED** [review]
Good catch :+1:

**Review by larkox — APPROVED** [review]
Thanks!

**Comment by larkox** [comment]
@hanzei Who should we assign here as QA reviewer?

**Comment by hanzei** [comment]
That would be @DHaussermann

**Comment by larkox** [comment]
@DHaussermann Friendly reminder on this.

**Comment by larkox** [comment]
@DHaussermann Friendly reminder on this

**Comment by larkox** [comment]
@DHaussermann Friendly reminder on this

**Comment by hanzei** [comment]
Let's merge this as it is

**Pull request merged**
