### PR TITLE
MM-19902 - Added example of channel header dropdown menu item

### PR DESCRIPTION
**Pull request by marianunez**
#### Summary

Added example of a menu item in the Channel Header Dropdown that opens the root modal. 

#### Ticket Link
[MM-19902](https://mattermost.atlassian.net/browse/MM-19902)

#### Screenshot

Screen Shot 2019-11-28 at 9 19 11 AM

#### Related Pull Requests

- Requires WebApp PR https://github.com/mattermost/mattermost-webapp/pull/4361

### CODE REVIEW

**Comment by prapti** [comment]
@marianunez The channel header dropdown added does not seem to be within it's own divided section (see screenshot below) as displayed on the example you've posted in the description.

Screen Shot 2019-12-18 at 5 35 38 PM

**Comment by kfilimon** [comment]
Hi, just wanted to let you know that this commit is causing issues when integrating plugin in mattermost running under docker preview image https://hub.docker.com/r/mattermost/mattermost-preview
two concerns in this commit are: 1) version 5.20 is too high 2) something with the new UI component is breaking the UI completely; the first was addressed by downgrading to 5.18, but the second i didn't have to dig in
by reverting this PR commit from master I was able to run the plugin

**Comment by kfilimon** [comment]
just out of curiosity: how can version be 5.20 if the last release (today) is 5.19?

**Comment by marianunez** [comment]
Hi @kfilimon, thanks for reaching out. 

1) The master branch of Mattermost both webApp and server are currently in v5.20 and we include some of the latest features in this plugin for demo and testing purposes. This is why this plugin currently requires a minimum server version of 5.20.
2) When you upload a plugin that requires a higher version it should provide an error and not be able to enable. It should not break the UI completely. Thank you for reporting this and will investigate why that is happening for you. 

You can use a previous release of the demo plugin that should be compatible with v5.19: https://github.com/mattermost/mattermost-plugin-demo/releases/tag/v0.3.0

**Comment by kfilimon** [comment]
Thank you @marianunez 
All clear now!

**Pull request merged**
