### PR TITLE
Feature/add messageswillbeconsumed hook demo

### PR DESCRIPTION
**Pull request by topolovac**
Adding MessagesWillBeConsumed hook demo. 
Hook was recently merged into master with this PR: https://github.com/mattermost/mattermost/pull/23305

Tagging @qryptdev

### CODE REVIEW

**Review by hanzei — CHANGES_REQUESTED** [review]
Hey @topolovac,

Thanks for your contribution :tada: Would you be open to signing the CLA as mentioned in https://github.com/mattermost/mattermost-plugin-demo/pull/168#issuecomment-1781417293? After that, I'm happy to review your PR. Thanks!

**Review by hanzei — APPROVED** [review]

**Comment by hanzei** [comment]
LGTM :+1:

**Review by lieut-data — APPROVED** [review]
Brilliant, thanks @topolovac!

**Review by saturninoabril — APPROVED** [review]
Sorry for the delay and thanks @topolovac for your contribution!

**Pull request merged**
