### PR TITLE
Add MessageHasBeenDeleted hook

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

Created to test https://github.com/mattermost/mattermost-server/pull/22476

### CODE REVIEW

**Review by hanzei — APPROVED** [review]

**Comment by mickmister** [comment]
Closing in favor of https://github.com/mattermost/mattermost-plugin-demo/pull/166

**Comment by hanzei** [comment]
@mickmister I'm confused. This PR exercises `MessageHasBeenDeleted` and https://github.com/mattermost/mattermost-plugin-demo/pull/166 exercises `UserHasBeenDeactivated`. Should we keep both open?

**Comment by mickmister** [comment]
@hanzei Indeed I got mixed up. Too many hooks being added at once and related PRs 🙂

**Comment by hanzei** [comment]
Closing as https://github.com/mattermost/mattermost-plugin-demo/pull/165 has been merged

**Pull request closed without merging**
