### PR TITLE
Add example usage of outgoing webhooks

### PR DESCRIPTION
**Pull request by hanzei**
#### Summary
Screenshot from 2023-11-08 15-08-42

#### Ticket Link
For https://github.com/mattermost/mattermost/pull/23805

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by DHaussermann** [comment]
@hanzei I have a bit of a silly problem. I can't get the build for this. 
Locally when I build I get these errors. I have tried using various versions of node and it did not solve it. 
image

Perhaps more important than whatever is happening on my local... I see the pipeline can build it just fine but I don't know how to go get the artifact. Has this UI changed? 
image
Where do I go get this? I think there use to be a grren button in the UI that I no longer see. But that may have never been the case for this repo.

Please let me know if you can provide some guidance.

**Comment by DHaussermann** [comment]
@hanzei I may ned help on this again. 
I'm afraid this isn't related to your PR but I can't make a working outgoing webhook to test with. I set the callback to some URL where the is no app waiting for the request but that should not matter for what I'm doing. 

I see an error when it trues to fire the hook.
```
{
  "caller": "app/webhook.go:120",
  "error": "doOutgoingWebhookRequest: Failed to unmarshal., invalid character 'T' looking for beginning of value",
  "ip_addr": "74.15.38.100",
  "level": "error",
  "method": "POST",
  "msg": "Event POST failed.",
  "path": "/api/v4/posts",
  "request_id": "kneiybqcet868b34tircbf7tsr",
  "timestamp": "2023-12-07 22:19:10.556 Z",
  "user_id": "sn41xt7ktjyapy36xn454f144c"
}
```

Please advise what I may be missing here. It's not clear to me what value stats with `T` that I need to adjust.

**Comment by hanzei** [comment]
@DHaussermann Can you please share a screenshot of settings that your Outgoing Webhook uses?

**Comment by DHaussermann** [comment]
@hanzei When I set this up again on a new `/cloud` server it was working. Possibly there was a typo or some other config error. It's just strange because I also tried loacaly with a `localhost:8065` calback URL  
Probably of little interest to you know but here is the config...
image

**Review by DHaussermann — APPROVED** [review]
Tested and passed 
- Demo plugin now provided a mechanism for testing outgoing webhook that posts a response as expected
- Setup is documented. 
- I ended up not needing the logging but I did try with an incorrect callback URL and confirmed and error clearly shows a failure for an outgoing webhook and provides details.

LGTM!

Huge thanks @hanzei this is a great enhancement that will help facilitate future testing! 🎉

**Pull request merged**
